# %% [markdown]
# # Notebook 01 — FMO Dataset Exploration
#
# This notebook visualises the dataset generated by `src/generate_data.py`.
# We examine:
# - The distribution of physical parameters across the sweep
# - Representative density matrix trajectories at different temperatures
# - The ENAQT signature: non-monotonic transfer efficiency vs dephasing rate
# - Coherence lifetimes as a function of T and λ
# - Data quality checks (trace conservation, positivity)
#
# **Run this after** `python src/generate_data.py` has completed.
#
# Convert to a Jupyter notebook with:
# ```bash
# jupytext --to notebook notebooks/01_data_exploration.py
# ```

# %%
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(".")), "src"))

import h5py
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

from src.utils import (
    load_config,
    extract_populations,
    extract_coherence_12,
    compute_trace,
    set_plot_style,
    dephasing_rate_cm,
    K_B_CM_PER_K,
    HBAR_CM_FS,
)

set_plot_style()
cfg = load_config("config.yaml")
hdf5_path = cfg["data"]["hdf5_path"]
print(f"Loading dataset from: {hdf5_path}")

# %% [markdown]
# ## 1. Dataset overview

# %%
with h5py.File(hdf5_path, "r") as f:
    n_traj   = f["trajectories/params"].shape[0]
    n_steps  = f["trajectories/rho_flat"].shape[1]
    t_fs     = f["trajectories/t_fs"][:]
    params   = f["trajectories/params"][:]      # (n_traj, 4)
    eff      = f["trajectories/efficiency"][:]  # (n_traj,)
    # Load a subset of trajectories for plotting
    rho_sample = f["trajectories/rho_flat"][:20]  # (20, n_steps, 18)

print(f"Dataset summary")
print(f"  Total trajectories: {n_traj}")
print(f"  Time steps:         {n_steps}")
print(f"  Time range:         {t_fs[0]:.0f} – {t_fs[-1]:.0f} fs")
print(f"  rho_flat shape:     (n_traj, {n_steps}, 18)")
print()
print(f"Parameter ranges:")
pnames = ["T (K)", "λ (cm⁻¹)", "ω_c (cm⁻¹)", "α"]
for i, name in enumerate(pnames):
    print(f"  {name:12s}: {params[:,i].min():.1f} – {params[:,i].max():.1f}")
print()
print(f"Transfer efficiency: mean={eff.mean():.4f}, std={eff.std():.4f}")

# %% [markdown]
# ## 2. Parameter distribution

# %%
fig, axes = plt.subplots(1, 4, figsize=(15, 3.5))
colors = ["#4C72B0", "#DD8452", "#55A868", "#C44E52"]

for i, (ax, name, color) in enumerate(zip(axes, pnames, colors)):
    unique_vals = np.unique(params[:, i])
    counts = [(params[:, i] == v).sum() for v in unique_vals]
    ax.bar(range(len(unique_vals)), counts, color=color, alpha=0.8, edgecolor="white")
    ax.set_xticks(range(len(unique_vals)))
    ax.set_xticklabels([f"{v:.0f}" for v in unique_vals], rotation=45, fontsize=9)
    ax.set_title(f"Distribution of {name}")
    ax.set_xlabel(name)
    ax.set_ylabel("Count" if i == 0 else "")

fig.suptitle("Parameter Sweep Distribution", fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig("results/figures/01_param_distribution.png", dpi=150, bbox_inches="tight")
plt.show()

# %% [markdown]
# ## 3. Representative trajectories at different temperatures
#
# Each panel shows the coherence |ρ₁₂(t)| and site populations P₁(t), P₂(t), P₃(t)
# for a fixed parameter set at each of the 5 temperatures in the sweep.

# %%
# Find trajectory indices for each temperature (fix λ=55, ω_c=100, α=1.0)
target_lambda   = 55.0   # closest available
target_omega_c  = 100.0
target_alpha    = 1.0
T_values        = cfg["sweep"]["T_K"]

# Find closest λ
lambda_vals = np.unique(params[:, 1])
target_lambda = lambda_vals[np.argmin(np.abs(lambda_vals - target_lambda))]

fig = plt.figure(figsize=(16, 10))
gs  = gridspec.GridSpec(2, len(T_values), hspace=0.45, wspace=0.3)

with h5py.File(hdf5_path, "r") as f:
    for col, T in enumerate(T_values):
        # Find matching trajectory
        mask = (
            (params[:, 0] == T) &
            (np.isclose(params[:, 1], target_lambda, atol=1.0)) &
            (np.isclose(params[:, 2], target_omega_c, atol=1.0)) &
            (np.isclose(params[:, 3], target_alpha, atol=0.01))
        )
        idx = np.where(mask)[0]
        if len(idx) == 0:
            continue
        idx = idx[0]

        rho_flat = f["trajectories/rho_flat"][idx]
        pops = extract_populations(rho_flat)
        coh  = extract_coherence_12(rho_flat)

        # Top row: coherence
        ax_top = fig.add_subplot(gs[0, col])
        ax_top.plot(t_fs, coh, color="purple", lw=1.8)
        ax_top.fill_between(t_fs, 0, coh, alpha=0.15, color="purple")
        ax_top.set_title(f"T = {T:.0f} K", fontsize=11, fontweight="bold")
        ax_top.set_ylabel(r"$|\rho_{12}(t)|$" if col == 0 else "")
        ax_top.set_ylim(-0.02, 0.55)
        if col == 0:
            ax_top.set_xlabel("Time (fs)")

        # Bottom row: populations
        ax_bot = fig.add_subplot(gs[1, col])
        ax_bot.plot(t_fs, pops[:, 0], "-",  lw=1.6, label=r"$P_1$", color="#4C72B0")
        ax_bot.plot(t_fs, pops[:, 1], "--", lw=1.6, label=r"$P_2$", color="#DD8452")
        ax_bot.plot(t_fs, pops[:, 2], "-.", lw=1.6, label=r"$P_3$", color="#55A868")
        ax_bot.set_ylabel("Population" if col == 0 else "")
        ax_bot.set_xlabel("Time (fs)")
        ax_bot.set_ylim(-0.02, 1.05)
        if col == 0:
            ax_bot.legend(fontsize=9, loc="upper right")

fig.suptitle(
    f"FMO Dynamics at Different Temperatures\n"
    f"(λ={target_lambda:.0f} cm⁻¹, ω_c={target_omega_c:.0f} cm⁻¹, α={target_alpha:.1f})",
    fontsize=13,
)
plt.savefig("results/figures/01_temperature_comparison.png", dpi=150, bbox_inches="tight")
plt.show()

# %% [markdown]
# ## 4. ENAQT signature in ground-truth data
#
# Environment-Assisted Quantum Transport (Rebentrost et al. 2009) predicts that
# transfer efficiency should be **non-monotonic** in the dephasing rate.
# At zero dephasing → Anderson localisation → poor transport.
# At optimal dephasing → quantum + classical paths interfere constructively.
# At very high dephasing → quantum Zeno effect → poor transport again.
#
# Here we plot efficiency vs dephasing rate from the raw simulation data.

# %%
# Compute dephasing rates for all trajectories
gamma_phi_list = []
for i in range(len(params)):
    T_K, lam, omc, alpha = params[i]
    gp = dephasing_rate_cm(T_K, lam, omc, alpha)
    gamma_phi_list.append(gp)
gamma_phi_arr = np.array(gamma_phi_list)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Left: efficiency vs dephasing rate, colour by T
sc = axes[0].scatter(
    gamma_phi_arr, eff,
    c=params[:, 0], cmap="plasma",
    alpha=0.5, s=20, edgecolors="none"
)
plt.colorbar(sc, ax=axes[0], label="T (K)")
axes[0].set_xlabel(r"Dephasing rate $\gamma_\phi$ (cm$^{-1}$)")
axes[0].set_ylabel("Transfer Efficiency")
axes[0].set_title("ENAQT: Efficiency vs Dephasing Rate")
axes[0].set_xscale("log")

# Right: efficiency vs dephasing rate, colour by λ
sc2 = axes[1].scatter(
    gamma_phi_arr, eff,
    c=params[:, 1], cmap="viridis",
    alpha=0.5, s=20, edgecolors="none"
)
plt.colorbar(sc2, ax=axes[1], label=r"$\lambda$ (cm$^{-1}$)")
axes[1].set_xlabel(r"Dephasing rate $\gamma_\phi$ (cm$^{-1}$)")
axes[1].set_ylabel("Transfer Efficiency")
axes[1].set_title("ENAQT: Efficiency vs Dephasing Rate (colour = λ)")
axes[1].set_xscale("log")

plt.tight_layout()
plt.savefig("results/figures/01_enaqt_raw.png", dpi=150, bbox_inches="tight")
plt.show()

# %% [markdown]
# ## 5. Coherence lifetime vs temperature
#
# Theory predicts Γ₂ ≈ Γ₁/2 + γ_φ(T) ∝ T for the Ohmic spin-boson bath.
# We check whether this linear scaling is visible in the simulated data.

# %%
from scipy.optimize import curve_fit

def exp_decay(t, A, Gamma2, C):
    return A * np.exp(-Gamma2 * t) + C

fig, ax = plt.subplots(figsize=(8, 5))

T_unique = np.unique(params[:, 0])
colors_T = plt.cm.plasma(np.linspace(0.15, 0.85, len(T_unique)))

for T_val, col in zip(T_unique, colors_T):
    # Get all trajectories at this temperature
    mask = params[:, 0] == T_val
    rates = []

    with h5py.File(hdf5_path, "r") as f:
        idxs = np.where(mask)[0][:20]  # limit for speed
        for idx in idxs:
            coh = extract_coherence_12(f["trajectories/rho_flat"][idx])
            try:
                popt, _ = curve_fit(
                    exp_decay, t_fs, coh,
                    p0=[coh[0], 1/300, coh[-1]],
                    bounds=([0, 1e-6, 0], [1, 1, 1]),
                    maxfev=1000,
                )
                rates.append(popt[1])
            except:
                pass

    if rates:
        rates = np.array(rates)
        ax.scatter(
            np.full_like(rates, T_val) + np.random.uniform(-3, 3, len(rates)),
            rates * 1000,   # convert to 1/ps for readability
            color=col, alpha=0.6, s=30, label=f"T={T_val:.0f} K"
        )
        ax.errorbar(T_val, np.mean(rates) * 1000,
                    yerr=np.std(rates) * 1000,
                    fmt="D", color=col, markersize=8, capsize=4, lw=2)

ax.set_xlabel("Temperature T (K)", fontsize=12)
ax.set_ylabel(r"$\Gamma_2$ (ps$^{-1}$)", fontsize=12)
ax.set_title(r"Coherence Decoherence Rate $\Gamma_2$ vs Temperature", fontsize=12)
ax.legend(fontsize=9, ncol=2)
plt.tight_layout()
plt.savefig("results/figures/01_decoherence_vs_T.png", dpi=150, bbox_inches="tight")
plt.show()

# %% [markdown]
# ## 6. Data quality checks
#
# Verify that all simulated density matrices satisfy the basic physical constraints:
# - Tr(ρ) ≈ 1 (exact at t=0; decreases due to sink)
# - ρ_ii ≥ 0 (populations non-negative)
# - |ρ_12| ≤ sqrt(ρ_11 * ρ_22) (off-diagonal bounded by geometric mean of populations)

# %%
print("Running data quality checks...")

n_violations_trace   = 0
n_violations_pos     = 0
n_violations_bound   = 0
n_checked = 0

with h5py.File(hdf5_path, "r") as f:
    for i in range(min(n_traj, 500)):
        rho = f["trajectories/rho_flat"][i]    # (n_steps, 18)
        tr  = compute_trace(rho)               # (n_steps,)
        pops = extract_populations(rho)        # (n_steps, 3)
        coh  = extract_coherence_12(rho)       # (n_steps,)

        # At t=0, trace should be very close to 1
        if abs(tr[0] - 1.0) > 0.01:
            n_violations_trace += 1

        # Populations should never be negative (by much)
        if np.any(pops < -0.01):
            n_violations_pos += 1

        # |ρ₁₂| ≤ sqrt(P₁ P₂)
        bound = np.sqrt(np.clip(pops[:, 0] * pops[:, 1], 0, None))
        if np.any(coh > bound + 0.01):
            n_violations_bound += 1

        n_checked += 1

print(f"Checked {n_checked} trajectories:")
print(f"  Trace violations (|Tr(ρ(0)) - 1| > 0.01): {n_violations_trace}")
print(f"  Positivity violations (ρ_ii < -0.01):      {n_violations_pos}")
print(f"  Coherence bound violations:                 {n_violations_bound}")

# Plot trace evolution
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

with h5py.File(hdf5_path, "r") as f:
    traces_sample = []
    for i in range(0, min(n_traj, 50)):
        rho = f["trajectories/rho_flat"][i]
        traces_sample.append(compute_trace(rho))
    traces_sample = np.array(traces_sample)

axes[0].plot(t_fs, traces_sample.T, alpha=0.3, lw=0.8, color="steelblue")
axes[0].plot(t_fs, traces_sample.mean(axis=0), "k-", lw=2, label="Mean")
axes[0].set_xlabel("Time (fs)")
axes[0].set_ylabel("Tr(ρ)")
axes[0].set_title("Trace Evolution (50 trajectories)\nDecay due to reaction-centre sink")
axes[0].legend()

# Histogram of final trace
final_trace = traces_sample[:, -1]
axes[1].hist(final_trace, bins=20, color="steelblue", edgecolor="white", alpha=0.8)
axes[1].axvline(final_trace.mean(), color="red", lw=2, label=f"Mean={final_trace.mean():.3f}")
axes[1].set_xlabel("Tr(ρ) at t = 1000 fs")
axes[1].set_ylabel("Count")
axes[1].set_title("Distribution of Final Trace\n(1 − Tr = transfer efficiency)")
axes[1].legend()

plt.tight_layout()
plt.savefig("results/figures/01_data_quality.png", dpi=150, bbox_inches="tight")
plt.show()

# %% [markdown]
# ## 7. Correlation heatmap: efficiency vs parameter pairs
#
# A quick look at which parameter combinations most strongly influence
# the transfer efficiency — useful for understanding what the ML models
# need to learn.

# %%
fig, axes = plt.subplots(2, 3, figsize=(14, 9))
param_combos = [
    (0, 1, "T (K)", "λ (cm⁻¹)"),
    (0, 2, "T (K)", "ω_c (cm⁻¹)"),
    (0, 3, "T (K)", "α"),
    (1, 2, "λ (cm⁻¹)", "ω_c (cm⁻¹)"),
    (1, 3, "λ (cm⁻¹)", "α"),
    (2, 3, "ω_c (cm⁻¹)", "α"),
]

for ax, (i, j, xi, xj) in zip(axes.ravel(), param_combos):
    sc = ax.scatter(
        params[:, i], params[:, j],
        c=eff, cmap="viridis",
        alpha=0.6, s=30,
        edgecolors="none",
        vmin=eff.min(), vmax=eff.max(),
    )
    plt.colorbar(sc, ax=ax, label="Efficiency" if j == 3 else "")
    ax.set_xlabel(xi, fontsize=10)
    ax.set_ylabel(xj, fontsize=10)
    ax.set_title(f"Efficiency: {xi} × {xj}", fontsize=10)

fig.suptitle("Transfer Efficiency as a Function of Parameter Pairs", fontsize=13)
plt.tight_layout()
plt.savefig("results/figures/01_efficiency_correlations.png", dpi=150, bbox_inches="tight")
plt.show()

print("\nNotebook 01 complete. All figures saved to results/figures/")
